name: Build, Encrypt, and Deploy (StatiCrypt)
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      # 1) Build Eleventy + Pagefind
      - run: npm run build

      # 2) Encrypt HTML into ./encrypted
      - run: npx staticrypt "_site/**/*.html" "$SITE_PASSWORD" --recursive --salt "$SALT" --output-dir encrypted --template-title "Solutions Log"
        env:
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          SALT: ${{ secrets.SALT }}

      # 3) Copy non-HTML assets (CSS, JS, images, and the Pagefind bundle)
      - run: rsync -a --exclude='**/*.html' _site/ encrypted/

      # 4) Publish encrypted/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: encrypted
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
