name: Build & Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # 1) Build Eleventy output to _site
      - name: Build site
        run: npm run build

      # (Optional) If you add Pagefind back later:
      # - name: Build Pagefind index
      #   run: npx pagefind --source _site

      # 2) Make sure GitHub Pages serves static files as-is
      - name: Add .nojekyll
        run: touch _site/.nojekyll

      # (Optional) If you're using a custom domain with Cloudflare, uncomment:
      - name: Add CNAME
        run: echo "solutions.reubeningber.com" > _site/CNAME

      # 3) Sanity check: _site has a root index.html
      - name: Verify _site contents
        run: |
          ls -la _site | sed -n '1,200p'
          test -f _site/index.html

      # 4) Upload artifact for Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
